apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      volumes:
        - name: kafka-volume
          hostPath:
            path: /home/docker/kafka
            type: Directory
      containers:
        - name: kafka
          image: ligato/kafka-arm64:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 9094
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_auto_create_topics
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_advertised_listeners
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_listener_security_protocol_map
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_listener
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_zookeeper_connect
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_inter_broker_listener_name
            - name: KAFKA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_opts
            - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_sasl_mechanism_inter_broker_protocol
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_sasl_enabled_mechanisms
          volumeMounts:
            - name: kafka-volume
              mountPath: /etc/kafka
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      name: kafka-port-1
      port: 9093
      targetPort: 9093
    - protocol: TCP
      name: kafka-port-2
      port: 9094
      targetPort: 9094
    - port: 9092
      name: kafka-port
      protocol: TCP