spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/group19?currentSchema=group19
    driver-class-name: org.postgresql.Driver
    username: group19
    password: group19
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml
    default-schema: group19
    drop-first: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
group19:
  passwordRecoveryPath: change-password
  websiteHost: ${WEBSITE_HOST:localhost}
  frontendPort: ${FRONTEND_PORT:8099}
values:
  jwt:
    header: Authorization
    secretKey: secret
    expiration: 120
    refreshExpirationDateInMs: 9000000
  socketio:
    host: 0.0.0.0
    port: 9092
  cloudinary:
    secret:
    key:
    name:
embedded-postgresql:
  host: localhost
  port: 5432
  database: group19
  schema: group19
  user: group19
  password: group19
email_service:
  host: ${EMAIL_SERVICE_HOST:localhost}
  port: ${EMAIL_SERVICE_PORT:8081}

