server:
  port: 8086
spring:
  banner:
    location: banner.txt
  main:
    banner-mode: console
    log-startup-info: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/group19?currentSchema=group19
    driver-class-name: org.postgresql.Driver
    username: group19
    password: group19
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml
    default-schema: group19
    drop-first: ${DROP-FIRST:false}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

group19:
  passwordRecoveryPath: change-password
  websiteHost: ${WEBSITE_HOST:localhost}
  frontendPort: ${FRONTEND_PORT:80}
values:
  jwt:
    header: Authorization
    secretKey: ${SECRET_KEY:U0VDUkVUX0tFWVNFQ1JFVF9LRVlTRUNSRVRfS0VZU0VDUkVUX0tFWVNFQ1JFVF9LRVlTRUNSRVRfS0VZU0VDUkVUX0tFWVNFQ1JFVF9LRVk=}
    expiration: ${JWT_TOKEN_EXPIRATION:120}
    refreshExpirationDateInMs: 9000000
  socketio:
    host: 0.0.0.0
    port: 9092
  cloudinary:
    secret: ${cloudinary_api_secret}
    key: ${cloudinary_api_key}
    name: ${cloudinary_api_name}
  twilio:
    enableTwilio: true
    accountSid: "AC089ef24e7292d3687ed7891cdeeb5530"
    authToken: "08a5f1f7a3ff5759a1113bee3fc437a3"
    phoneNumber: "+19378835706"
  avatar:
    default: "http://res.cloudinary.com/dgkxuiwls/image/upload/v1643476971/v93wekx93czrslanwybs.jpg"
    deleted: "http://res.cloudinary.com/dgkxuiwls/image/upload/v1643476880/armg4dpkz16pvgedqgqy.jpg"
email_service:
  path: ${EMAIL_SERVICE_PATH:http://localhost:8080}