server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/group19?currentSchema=group19
    driver-class-name: org.postgresql.Driver
    username: group19
    password: group19
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: group19
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: javaproGroup19@gmail.com
    password: ${MAIL_SERVICE_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.timeout: 10000

group19:
  passwordRecoveryPath: change-password
  websiteHost: localhost
  frontendPort: 8099
values:
  jwt:
    header: Authorization
    secretKey: secret
    expiration: 604800