spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/group19?currentSchema=group19
    driver-class-name: org.postgresql.Driver
    username: group19
    password: group19
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml
    default-schema: group19
    drop-first: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: javaproGroup19@gmail.com
    password: ${MAIL_SERVICE_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.timeout: 10000

group19:
  passwordRecoveryPath: change-password
  websiteHost: ${WEBSITE_HOST:localhost}
  frontendPort: ${FRONTEND_PORT:8099}
values:
  jwt:
    header: Authorization
    secretKey: secret
    expiration: 120
    refreshExpirationDateInMs: 9000000
embedded-postgresql:
  host: localhost
  port: 5432
  database: group19
  schema: group19
  user: group19
  password: group19
