server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/new
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12341234
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none